### ISSUE TITLE
Two questions from a Frida documentation newbie

### ISSUE THREAD

**Issue by mosherubin** [frida/frida-website#147]
Hi,

Having recently submitted my first pull request for frida-trace, I would like to take the time to enhance the frida-trace documentation as I wish it would have been when I started using the tool.  I have two questions to help get me started:

- What is the specific markdown flavor used for Frida documentation, and where can I find an online specification of this markdown?  The style used does not seem to conform to GitHub's syntax (https://guides.github.com/features/mastering-markdown/).

- Is there a way for me to generate the HTML from the markdown file so I can check the look-and-feel before committing and issuing a pull request?

Thanks in advance,

Moshe Rubin

**Comment by oleavr** [comment]
Hi,

That would be awesome!

> What is the specific markdown flavor used for Frida documentation
We're using Jekyll, some docs [here](https://jekyllrb.com/docs/posts/). Our website is actually a fork of theirs, so looking at their website's source code might be helpful for examples.

> Is there a way for me to generate the HTML from the markdown file so I can check the look-and-feel before committing and issuing a pull request?

Yes `jekyll serve -w` if I remember correctly.

Cheers!

**Comment by mosherubin** [comment]
I installed Ruby + Jekyll on my Windows system and ran into too many problems, including problems with `tzinfo` and more.

I then installed Ruby + Jekyll on Windows Subsystem Linux (WSL) as per the Jekyll site's instructions and have run into problems (see following):

```
moshe@TAL:/mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website$ jekyll serve -w --trace
Configuration file: /mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website/_config.yml
            Source: /mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website
       Destination: /mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
             Error: could not read file /mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website/_docs/frida-trace.md.SAVE: invalid byte sequence in UTF-8
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Liquid syntax error (/mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website/_includes/top.html line 11): Unknown tag 'seo' included in /_layouts/default.html
Traceback (most recent call last):
        52: from /usr/local/bin/jekyll:23:in `<main>'
        51: from /usr/local/bin/jekyll:23:in `load'
        50: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        49: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        48: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        47: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        46: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        45: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        44: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        43: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        42: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        41: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'        40: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
        39: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
        38: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
        37: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
        36: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
        35: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
        34: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
        33: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
        32: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
        31: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
        30: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
        29: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
        28: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:89:in `render_document'
        27: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:159:in `place_in_layouts'
        26: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:196:in `render_layout'
        25: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:127:in `render_liquid'
        24: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:32:in `render!'
        23: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
        22: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:33:in `block in render!'
        21: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:53:in `measure_bytes'
        20: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:34:in `block (2 levels) in render!'
        19: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_counts'
        18: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:35:in `block (3 levels) in render!'
        17: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        16: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        15: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        14: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        13: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        12: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        11: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:120:in `render'
        10: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:154:in `load_cached_partial'
         9: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
         8: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
         7: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
         6: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
         5: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
         4: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
         3: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
         2: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
         1: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:11:in `block in parse'
/var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (/mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website/_includes/top.html line 11): Unknown tag 'seo' included  (Liquid::SyntaxError)
moshe@TAL:/mnt/d/Private/Dev/Open-Source-Projects/frida/frida-website$  
```  

Why is it that there is an invalid UTF-8 sequence in the frida-trace.md file?  And what do I need to do to make Jekyll understand the `seo` tag?  Once I have Jekyll running I plan on updating / enhancing much of the frida-trace documentation.

**Comment by oleavr** [comment]
You need to install [these](https://github.com/frida/frida-website/blob/9b239f3484f3ec3e03ad1fda2a76d35852f662e6/_config.yml#L27-L33) gems. We should definitely document that.
