### ISSUE TITLE
run errro in the mac 10.15.3  python version 3.7.4

### ISSUE THREAD

**Issue by ReturnHere** [frida/frida-website#166]
frida --version
Traceback (most recent call last):
  File "/usr/local/bin/frida", line 11, in <module>
    load_entry_point('frida-tools==6.0.1', 'console_scripts', 'frida')()
  File "/Library/Python/2.7/site-packages/frida_tools/repl.py", line 25, in main
    from prompt_toolkit import PromptSession
  File "build/bdist.macosx-10.14-intel/egg/prompt_toolkit/__init__.py", line 16, in <module>
  File "build/bdist.macosx-10.14-intel/egg/prompt_toolkit/application/__init__.py", line 1, in <module>
  File "/Library/Python/2.7/site-packages/prompt_toolkit-3.0.3-py2.7.egg/prompt_toolkit/application/application.py", line 187
    layout: Optional[Layout] = None,
          ^
SyntaxError: invalid syntax

**Comment by 0z4ck** [comment]
similar problem here
WSL-ubuntu16.04
python 2.7.12
frida (12.8.20)
frida-tools (7.2.0)

```frida --version
Traceback (most recent call last):
  File "/home/z4ck/.local/bin/frida", line 11, in <module>
    sys.exit(main())
  File "/home/z4ck/.local/lib/python2.7/site-packages/frida_tools/repl.py", line 25, in main
    from prompt_toolkit import PromptSession
  File "/home/z4ck/.local/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/home/z4ck/.local/lib/python2.7/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/z4ck/.local/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 188
    layout: Optional[Layout] = None,
          ^
SyntaxError: invalid syntax
```

**Comment by 0z4ck** [comment]
ok, so 2 of frida-tools' dependencies do not support python2. 

If you still want to use python2,
prompt-toolkit should be v2 and pygments should be 2.5.2  or older.

pip uninstall prompt-toolkit
pip install prompt-toolkit==2.0.10
pip uninstall Pygments
pip install Pygments==2.5.2

or maybe you should switch to python3
