### ISSUE TITLE
undefined symbol: PyUnicodeUCS2_AsUTF8String

### ISSUE THREAD

**Issue by sagishahar** [frida/frida-website#19]
Hi,

As can be seen below, a straight forward install on Ubuntu 14.04. 
Please advise.

Thank you,
Sagi
```
x@x:~$ sudo easy_install frida
Searching for frida
Reading https://pypi.python.org/simple/frida/
Best match: frida 3.0.1
Downloading https://pypi.python.org/packages/2.7/f/frida/frida-3.0.1-py2.7-linux-x86_64.egg#md5=65481a60d5c84ac456e8e1933259c241
Processing frida-3.0.1-py2.7-linux-x86_64.egg
Moving frida-3.0.1-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Adding frida 3.0.1 to easy-install.pth file
Installing frida-repl script to /usr/local/bin
Installing frida-ps script to /usr/local/bin
Installing frida-trace script to /usr/local/bin
Installing frida-discover script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg
Processing dependencies for frida
Finished processing dependencies for frida
x@x:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> session = frida.attach("cat")

***
Failed to load the Frida native extension: /home/x/.python-eggs/frida-3.0.1-py2.7-linux-x86_64.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
Please ensure that the extension was compiled for Python 2.7.
***

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg/frida/__init__.py", line 16, in attach
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg/frida/__init__.py", line 84, in get_device_manager
ImportError: /home/x/.python-eggs/frida-3.0.1-py2.7-linux-x86_64.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
```

**Comment by sagishahar** [comment]
Sorry, I haven't seen the previous post that reported on the same issue. Closing this one.
