### ISSUE TITLE
Python 3.10 Error

### ISSUE THREAD

**Issue by syvdev** [frida/frida-website#222]
I get this error when loading the new frida with python 3.10

Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Users\Seven\AppData\Local\Programs\Python\Python310\Scripts\frida-ps-script.py", line 33, in <module>
    sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida-ps')())
  File "C:\Users\Seven\AppData\Local\Programs\Python\Python310\lib\site-packages\frida_tools\ps.py", line 17, in main
    from frida_tools.application import ConsoleApplication
  File "C:\Users\Seven\AppData\Local\Programs\Python\Python310\lib\site-packages\frida_tools\application.py", line 23, in <module>
    import frida
  File "C:\Users\Seven\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 24, in <module>
    raise ex
  File "C:\Users\Seven\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 7, in <module>
    import _frida
ImportError: DLL load failed while importing _frida: The specified module could not be found.

**Comment by keyiis** [comment]
I have same error.
Env: win10,Python 3.10,pip 21.3.1
```
>frida --version

***
Failed to load the Frida native extension: DLL load failed while importing _frida: 找不到指定的模块。
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\Scripts\frida-script.py", line 33, in <module>
    sys.exit(load_entry_point('frida-tools==10.4.1', 'console_scripts', 'frida')())
  File "D:\Program Files\Python\Python310\lib\site-packages\frida_tools\repl.py", line 24, in main
    import frida
  File "D:\Program Files\Python\Python310\lib\site-packages\frida\__init__.py", line 24, in <module>
    raise ex
  File "D:\Program Files\Python\Python310\lib\site-packages\frida\__init__.py", line 7, in <module>
    import _frida
ImportError: DLL load failed while importing _frida: 找不到指定的模块。
```

**Comment by blackxored** [comment]
It seems like the authors need to figure out what's wrong with 3.10, i installed 3.9 with `choco install python3 --version=3.9.9` and the `frida` command seems to work.

**Comment by sonwnja** [comment]
I also encountered the same error, and I can only change it to reinstall python3.9 so that the error will not be reported. It's really bullshit

**Comment by sonwnja** [comment]
I also encountered the same error, and I can only change it to reinstall python3.9 so that the error will not be reported. It's really bullshit
