### ISSUE TITLE
pip install frida-tools returen a error

### ISSUE THREAD

**Issue by EnjoMoonlight** [frida/frida-website#271]
pip install frida-tools
Processing /home/wxl/.cache/pip/wheels/a3/55/ba/d47fc0292871c146f5522f655a9a98698fa33ca85caedfdb08/frida_tools-12.3.0-py3-none-any.whl
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in /usr/lib/python3/dist-packages (from frida-tools) (2.3.1)
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /usr/lib/python3/dist-packages (from frida-tools) (0.4.3)
Collecting frida<17.0.0,>=16.0.9
  Using cached frida-16.2.1.tar.gz (41 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: prompt-toolkit<4.0.0,>=2.0.0 in /home/wxl/.local/lib/python3.8/site-packages (from frida-tools) (2.0.10)
Requirement already satisfied: typing-extensions; python_version < "3.11" in /home/wxl/.local/lib/python3.8/site-packages (from frida<17.0.0,>=16.0.9->frida-tools) (4.11.0)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools) (1.14.0)
Requirement already satisfied: wcwidth in /home/wxl/.local/lib/python3.8/site-packages (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools) (0.2.13)
Building wheels for collected packages: frida
  Building wheel for frida (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpn5184nh_ build_wheel /tmp/tmpvtqc5tc4
       cwd: /tmp/pip-install-xur9vor7/frida
  Complete output (67 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-38
  creating build/lib.linux-x86_64-cpython-38/frida
  copying frida/__init__.py -> build/lib.linux-x86_64-cpython-38/frida
  copying frida/core.py -> build/lib.linux-x86_64-cpython-38/frida
  copying frida/py.typed -> build/lib.linux-x86_64-cpython-38/frida
  creating build/lib.linux-x86_64-cpython-38/_frida
  copying _frida/__init__.pyi -> build/lib.linux-x86_64-cpython-38/_frida
  copying _frida/py.typed -> build/lib.linux-x86_64-cpython-38/_frida
  running build_ext
  Traceback (most recent call last):
    File "/tmp/tmpn5184nh_", line 280, in <module>
      main()
    File "/tmp/tmpn5184nh_", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpn5184nh_", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 102, in <module>
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-fedirpqa/normal/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
      _build_ext.run(self)
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
      self.build_extensions()
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
      self._build_extensions_serial()
    File "/tmp/pip-build-env-fedirpqa/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
      self.build_extension(ext)
    File "<string>", line 34, in build_extension
  RuntimeError: Need frida-core devkit to build from source.
  Download one from https://github.com/frida/frida/releases, extract it to a directory,
  and then add an environment variable named FRIDA_CORE_DEVKIT pointing at the directory.
  ----------------------------------------
  ERROR: Failed building wheel for frida
Failed to build frida
ERROR: Could not build wheels for frida which use PEP 517 and cannot be installed directly

who can tell me what was wrong,thanks

**Comment by vigneshsb403** [comment]
hey mate did you find any solution for this I am facing the same issue here
