### ISSUE TITLE
frida.NotSupportedError: unexpected error while mapping dylib (mach_vm_write(runtime) returned '(os/kern) invalid address')

### ISSUE THREAD

**Issue by zywu0221** [frida/frida-website#276]
TommydeMBP:~ root# python3 /Users/tommywu/Desktop/example.py
Traceback (most recent call last):
  File "/Users/tommywu/Desktop/example.py", line 6, in <module>
    session = frida.attach("cat")
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: unexpected error while mapping dylib (mach_vm_write(runtime) returned '(os/kern) invalid address')

**Comment by jpstotz** [comment]
This is the issue tracker of the frida website https://frida.re that presents the documentation, not of the frida tool itself.
