### ISSUE TITLE
 Unable to perform state transition

### ISSUE THREAD

**Issue by npynto** [frida/frida-website#278]
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}

Trying to reinstall and start frida-server 16.5.6 to Pixel 9 (rooted via Magisk 27.0) I get the above error. I previously had everything working, when running the smoke test I would get; Failed to enumerate applications: connection closed. adb can see my device.                    
When trying to use a codeshare or local file, I would get the following error: Failed to spawn: need Gadget to attach on jailed Android; its default location is: /Users/npynto/.cache/frida/gadget-android-arm64.so

All complementary, corresponding versions are aligned (eg frida tools etc). I have the following installed objection: 1.11.0.

**Comment by npynto** [comment]
Resolved by running this on the device `adb shell setenforce 0`
