### ISSUE TITLE
pip install with python3.5 requires python3.5-dev under ubuntu/mint

### ISSUE THREAD

**Issue by kung-foo** [frida/frida-website#49]
A clean install using python3.5 under Mint 17.3 (Ubuntu 14.04) requires the python3.5-dev package. pip installs frida without complaint. Maybe either better error message or an update to the docs?

```
$ python3.5
Python 3.5.1 (default, Dec 18 2015, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida

***
Failed to load the Frida native extension: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/frida/__init__.py", line 26, in <module>
    raise ex
  File "/usr/local/lib/python3.5/dist-packages/frida/__init__.py", line 6, in <module>
    import _frida
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
```

Fixed by doing an `apt-get install python3.5-dev`.

**Comment by oleavr** [comment]
Ooh, nice catch, thanks! The dev package should definitely not be needed, so it looks like we're linking against the wrong soname on Linux.

**Comment by oleavr** [comment]
Moving to frida-python.
