### ISSUE TITLE
DLL Error for windows

### ISSUE THREAD

**Issue by P3pito** [frida/frida-website#51]
Hi,

I just installed the new version 7.1.8 and tried to run a frida-ps -U:

```
C:\WINDOWS\system32>frida-ps -U

***
Failed to load the Frida native extension: DLL load failed: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Python34\Scripts\frida-ps-script.py", line 9, in <module> load_entry_point('frida==7.1.8', 'console_scripts', 'frida-ps')()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point return get_distribution(dist).load_entry_point(group, name)
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point return ep.load()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2355, in load return self.resolve()
  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python34\lib\site-packages\frida\__init__.py", line 26, in <module> raise ex
  File "c:\python34\lib\site-packages\frida\__init__.py", line 6, in <module> import _frida
ImportError: DLL load failed: The specified module could not be found.
```

I have both python34 and python27 installed as required (C:\python34 and C:\python27).
Paths added to the environment variable (+ \Scripts).

**Comment by oleavr** [comment]
Hey,

Could you try with python 3.5? The 3.x binaries were built for 3.5, and I suspect they're only compatible with that specific release.

Cheers!

**Comment by P3pito** [comment]
```
C:\WINDOWS\system32>frida-ps -U
Waiting for USB device to appear...
  PID  Name
-----  --------------------------------------------------
 4057  adbd
15127  android.process.acore
  968  android.process.media
  203  bridgemgrd
 1216  com.android.nfc
 1243  com.android.phone
  956  com.android.systemui
 7115  com.android.vending
15052  com.google.android.apps.fitness
13433  com.google.android.deskclock
10144  com.google.android.gms
 1192  com.google.android.gms.persistent
 1258  com.google.android.googlequicksearchbox
 1123  com.google.android.googlequicksearchbox:interactor
 1370  com.google.android.googlequicksearchbox:search
 1142  com.google.android.inputmethod.latin
14347  com.google.android.keep
14277  com.google.android.talk
 1412  com.google.process.gapps
 2205  com.qualcomm.qcrilmsgtunnel
 1228  com.redbend.vdmc
 6705  com.speedsoftware.rootexplorer
 1986  daemonsu:10085
 9370  daemonsu:10086
 9372  daemonsu:10086:9367
 6781  daemonsu:10090
  570  daemonsu:master
  517  daemonsu:mount:master
  196  debuggerd
  198  drmserver
15072  eu.chainfire.supersu
 9768  frida-server
  214  gatekeeperd
  189  healthd
    1  init
  200  installd
 9027  jackpal.androidterm
  202  keystore
  190  lmkd
  147  logd
  199  mediaserver
  217  mm-qcamera-daemon
 1572  mpdecision
  195  netd
  205  netmgrd
  204  qmuxd
  194  qseecomd
  228  qseecomd
  197  rild
  193  rmt_storage
  942  sdcard
  206  sensors.qcom
  191  servicemanager
 6733  sh
 6776  sh
 9049  sh
 6778  su
 9367  su
  192  surfaceflinger
 6783  sush
 9474  sush
  809  system_server
  209  thermal-engine-hh
  218  time_daemon
  131  ueventd
  148  vold
 7020  wpa_supplicant
  213  zygote
```

Man you are the best !
Now I'm gonna playyyy : )

Many thanks for your work and reactivity to people issues !

**Comment by oleavr** [comment]
Glad that solved it! Hope the latest versions are still working well for you :)
