### ISSUE TITLE
Failed to load the Frida native extension

### ISSUE THREAD

**Issue by piopro** [frida/frida-website#55]
Hi, I have got the error trying to install Frida for Windows: Failed to load the Frida native extension: DLL load failed: ..... Please ensure that the extension was compiled for Python 3.x.

The install procedure was:
1) Downloaded: https://www.python.org/ftp/python/3.6.0/python-3.6.0a3-amd64.exe
2) Executed: python-3.6.0a3-amd64.exe
3) Downloaded: https://bootstrap.pypa.io/ez_setup.py
4) Executed: python ez_setup.py --insecure 
5) Executed: pip install Frida
6) Executed: Frida

The output was 

Failed to load the Frida native extension: DLL load failed: Не найден указанный модуль.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Software\Python36\Scripts\frida-script.py", line 9, in <module>
    load_entry_point('frida==7.2.16', 'console_scripts', 'frida')()
  File "c:\software\python36\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\software\python36\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "c:\software\python36\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
    return self.resolve()
  File "c:\software\python36\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\software\python36\lib\site-packages\frida\__init__.py", line 26, in <module>
    raise ex
  File "c:\software\python36\lib\site-packages\frida\__init__.py", line 6, in <module>
    import _frida
ImportError: DLL load failed: Не найден указанный модуль.

What should I do to correct?

**Comment by piopro** [comment]
Solved this problem replacing Python distribution by this: https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe

**Comment by oleavr** [comment]
👍
