### ISSUE TITLE
macos install problems

### ISSUE THREAD

**Issue by dozens** [frida/frida-website#63]
Not sure what info you need but if this is not enough let me know.

$ sudo -H pip install frida
Collecting frida
  Downloading frida-8.1.1.zip
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.7 in /Library/Python/2.7/site-packages (from frida)
Collecting prompt-toolkit>=0.57 (from frida)
  Downloading prompt_toolkit-1.0.8-py2-none-any.whl (240kB)
    100% |████████████████████████████████| 245kB 2.2MB/s 
Collecting pygments>=2.0.2 (from frida)
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |████████████████████████████████| 757kB 1.2MB/s 
Collecting six>=1.9.0 (from prompt-toolkit>=0.57->frida)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit>=0.57->frida)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Installing collected packages: six, wcwidth, prompt-toolkit, pygments, frida
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-6Nqhkj-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
$ uname -a
Darwin Casalt001142s-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

**Comment by dozens** [comment]
I was able to resolve this issue by upgrading six. I download six-1.10.0.tar.gz and use"python setup.py install" to upgrade. frida was then able to install.
