### ISSUE TITLE
Failed to load the Frida native extension: libpython3.6m.so.1.0

### ISSUE THREAD

**Issue by pentatonicfunk** [frida/frida-website#81]
```
frida --version

***
Failed to load the Frida native extension: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/usr/local/bin/frida", line 7, in <module>
    from frida.repl import main
  File "/usr/local/lib/python3.5/dist-packages/frida/__init__.py", line 26, in <module>
    raise ex
  File "/usr/local/lib/python3.5/dist-packages/frida/__init__.py", line 6, in <module>
    import _frida
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
root@hendrawan-vb:~# apt install python3.5-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3.5-dev is already the newest version (3.5.2-2ubuntu0~16.04.1).
python3.5-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

installed frida using **pip3 install frida**

**Comment by oleavr** [comment]
The prebuilt 3.x binaries are for 3.6 only.
